//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoreanSportic.Web.Resources.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistroViewModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistroViewModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoreanSportic.Web.Resources.ViewModels.RegistroViewModelResources", typeof(RegistroViewModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Apellido_DisplayName {
            get {
                return ResourceManager.GetString("Apellido_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must contain only letters.
        /// </summary>
        public static string Apellido_Format {
            get {
                return ResourceManager.GetString("Apellido_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must be between {{2}} and {{1}} characters long.
        /// </summary>
        public static string Apellido_Length {
            get {
                return ResourceManager.GetString("Apellido_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string Apellido_Required {
            get {
                return ResourceManager.GetString("Apellido_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string ConfirmPassword_Compare {
            get {
                return ResourceManager.GetString("ConfirmPassword_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword_DisplayName {
            get {
                return ResourceManager.GetString("ConfirmPassword_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation is required.
        /// </summary>
        public static string ConfirmPassword_Required {
            get {
                return ResourceManager.GetString("ConfirmPassword_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email_DisplayName {
            get {
                return ResourceManager.GetString("Email_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        public static string Email_Required {
            get {
                return ResourceManager.GetString("Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must end with a valid domain (.com, .org, .es, etc.).
        /// </summary>
        public static string Email_Tld {
            get {
                return ResourceManager.GetString("Email_Tld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Nombre_DisplayName {
            get {
                return ResourceManager.GetString("Nombre_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name must contain only letters.
        /// </summary>
        public static string Nombre_Format {
            get {
                return ResourceManager.GetString("Nombre_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name must be between {{2}} and {{1}} characters long.
        /// </summary>
        public static string Nombre_Length {
            get {
                return ResourceManager.GetString("Nombre_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string Nombre_Required {
            get {
                return ResourceManager.GetString("Nombre_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password_DisplayName {
            get {
                return ResourceManager.GetString("Password_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be between {{2}} and {{1}} characters long.
        /// </summary>
        public static string Password_Length {
            get {
                return ResourceManager.GetString("Password_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain at least one uppercase letter, one lowercase letter, one number, and one special character.
        /// </summary>
        public static string Password_Strength {
            get {
                return ResourceManager.GetString("Password_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Sexo_DisplayName {
            get {
                return ResourceManager.GetString("Sexo_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Telefono_DisplayName {
            get {
                return ResourceManager.GetString("Telefono_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string Telefono_Invalid {
            get {
                return ResourceManager.GetString("Telefono_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string TipoUsuario_DisplayName {
            get {
                return ResourceManager.GetString("TipoUsuario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid role.
        /// </summary>
        public static string TipoUsuario_Range {
            get {
                return ResourceManager.GetString("TipoUsuario_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User role is required.
        /// </summary>
        public static string TipoUsuario_Required {
            get {
                return ResourceManager.GetString("TipoUsuario_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName_DisplayName {
            get {
                return ResourceManager.GetString("UserName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only letters, numbers, dot, hyphen, and underscore are allowed.
        /// </summary>
        public static string UserName_Format {
            get {
                return ResourceManager.GetString("UserName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be between {{2}} and {{1}} characters long.
        /// </summary>
        public static string UserName_Length {
            get {
                return ResourceManager.GetString("UserName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UserName_Required {
            get {
                return ResourceManager.GetString("UserName_Required", resourceCulture);
            }
        }
    }
}
