//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoreanSportic.Application.DTOs.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductoDTO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductoDTO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoreanSportic.Application.DTOs.Resources.ProductoDTO", typeof(ProductoDTO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string DescripcionLongitud {
            get {
                return ResourceManager.GetString("DescripcionLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string DescripcionRequerida {
            get {
                return ResourceManager.GetString("DescripcionRequerida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string IdCategoriaRequerido {
            get {
                return ResourceManager.GetString("IdCategoriaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string IdMarcaRequerido {
            get {
                return ResourceManager.GetString("IdMarcaRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string ImagenesProductoRequerido {
            get {
                return ResourceManager.GetString("ImagenesProductoRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string NombreLongitud {
            get {
                return ResourceManager.GetString("NombreLongitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string NombreRequerido {
            get {
                return ResourceManager.GetString("NombreRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string PrecioBaseDecimales {
            get {
                return ResourceManager.GetString("PrecioBaseDecimales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string PrecioBaseRango {
            get {
                return ResourceManager.GetString("PrecioBaseRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string PrecioBaseRequerido {
            get {
                return ResourceManager.GetString("PrecioBaseRequerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string StockNumerico {
            get {
                return ResourceManager.GetString("StockNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string StockRango {
            get {
                return ResourceManager.GetString("StockRango", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescripcionLongitud.
        /// </summary>
        public static string StockRequerido {
            get {
                return ResourceManager.GetString("StockRequerido", resourceCulture);
            }
        }
    }
}
